legend = ["LAT_ACCEL_FACTOR", "MAX_LAT_ACCEL_MEASURED", "FRICTION"]
### angle control
# Nissan appears to have torqu, 0.0, 0.0e
"NISSAN_XTRAIL" = [nan, 1.5, nan, 0.0, 0.0]
"NISSAN_ALTIMA" = [nan, 1.5, nan, 0.0, 0.0]
"NISSAN_LEAF_IC" = [nan, 1.5, nan, 0.0, 0.0]
"NISSAN_LEAF" = [nan, 1.5, nan, 0.0, 0.0]
"NISSAN_ROGUE" = [nan, 1.5, nan, 0.0, 0.0]

# New subarus angle based controller, 0.0, 0.0s
"SUBARU_FORESTER_2022" = [nan, 3.0, nan, 0.0, 0.0]
"SUBARU_OUTBACK_2023" = [nan, 3.0, nan, 0.0, 0.0]
"SUBARU_ASCENT_2023" = [nan, 3.0, nan, 0.0, 0.0]

# Toyota LTA also has torqu, 0.0, 0.0e
"TOYOTA_RAV4_TSS2_2023" = [nan, 3.0, nan, 0.0, 0.0]

# Tesla angle based controller, 0.0, 0.0s
"TESLA_MODEL_3" = [nan, 2.5, nan, 0.0, 0.0]
"TESLA_MODEL_Y" = [nan, 2.5, nan, 0.0, 0.0]

# Guess
"FORD_BRONCO_SPORT_MK1" = [nan, 1.5, nan, 0.0, 0.0]
"FORD_ESCAPE_MK4" = [nan, 1.5, nan, 0.0, 0.0]
"FORD_ESCAPE_MK4_5" = [nan, 1.5, nan, 0.0, 0.0]
"FORD_EXPLORER_MK6" = [nan, 1.5, nan, 0.0, 0.0]
"FORD_F_150_MK14" = [nan, 1.5, nan, 0.0, 0.0]
"FORD_FOCUS_MK4" = [nan, 1.5, nan, 0.0, 0.0]
"FORD_MAVERICK_MK1" = [nan, 1.5, nan, 0.0, 0.0]
"FORD_F_150_LIGHTNING_MK1" = [nan, 1.5, nan, 0.0, 0.0]
"FORD_MUSTANG_MACH_E_MK1" = [nan, 1.5, nan, 0.0, 0.0]
"FORD_RANGER_MK2" = [nan, 1.5, nan, 0.0, 0.0]
###

# No steering whee, 0.0, 0.0l
"COMMA_BODY" = [nan, 1000, nan, 0.0, 0.0]

# Totally new car, 0.0, 0.0s
"RAM_1500_5TH_GEN" = [2.0, 2.0, 0.05, 0.0, 0.0]
"RAM_HD_5TH_GEN" = [1.4, 1.4, 0.05, 0.0, 0.0]
"SUBARU_OUTBACK" = [2.0, 1.5, 0.2, 0.0, 0.0]
"CADILLAC_ESCALADE" = [1.899999976158142, 1.842270016670227, 0.1120000034570694, 0.0, 0.0]
"CADILLAC_ESCALADE_ESV_2019" = [1.15, 1.3, 0.2, 0.0, 0.0]
"CADILLAC_XT4" = [1.45, 1.6, 0.2, 0.0, 0.0]
"CHEVROLET_BOLT_EUV" = [1.0, 2.0, 0.175, 0.0, 0.0]
"CHEVROLET_SILVERADO" = [1.9, 1.9, 0.112, 0.0, 0.0]
"CHEVROLET_TRAILBLAZER" = [1.33, 1.9, 0.16, 0.0, 0.0]
"CHEVROLET_TRAVERSE" = [1.33, 1.33, 0.18, 0.0, 0.0]
"CHEVROLET_EQUINOX" = [2.5, 2.5, 0.05, 0.0, 0.0]
"CHEVROLET_VOLT_2019" = [1.4, 1.4, 0.16, 0.0, 0.0]
"VOLKSWAGEN_CADDY_MK3" = [1.2, 1.2, 0.1, 0.0, 0.0]
"VOLKSWAGEN_PASSAT_NMS" = [2.5, 2.5, 0.1, 0.0, 0.0]
"VOLKSWAGEN_SHARAN_MK2" = [2.5, 2.5, 0.1, 0.0, 0.0]
"HYUNDAI_SANTA_CRUZ_1ST_GEN" = [2.7, 2.7, 0.1, 0.0, 0.0]
"KIA_SPORTAGE_5TH_GEN" = [2.6, 2.6, 0.1, 0.0, 0.0]
"GENESIS_GV70_1ST_GEN" = [2.42, 2.42, 0.1, 0.0, 0.0]
"GENESIS_GV60_EV_1ST_GEN" = [2.5, 2.5, 0.1, 0.0, 0.0]
"GMC_YUKON" = [1.2, 2.5, 0.26, 0.0, 0.0]
"KIA_SORENTO_4TH_GEN" = [2.5, 2.5, 0.1, 0.0, 0.0]
"KIA_SORENTO_HEV_4TH_GEN" = [2.5, 2.5, 0.1, 0.0, 0.0]
"KIA_NIRO_HEV_2ND_GEN" = [2.42, 2.5, 0.12, 0.0, 0.0]
"KIA_NIRO_EV_2ND_GEN" = [2.05, 2.5, 0.14, 0.0, 0.0]
"GENESIS_GV80" = [2.5, 2.5, 0.1, 0.0, 0.0]
"KIA_CARNIVAL_4TH_GEN" = [1.75, 1.75, 0.15, 0.0, 0.0]
"GMC_ACADIA" = [1.6, 1.6, 0.2, 0.0, 0.0]
"LEXUS_IS_TSS2" = [2.0, 2.0, 0.1, 0.0, 0.0]
"HYUNDAI_KONA_EV_2ND_GEN" = [2.5, 2.5, 0.1, 0.0, 0.0]
"HYUNDAI_IONIQ_6" = [2.5, 2.5, 0.005, 0.0, 0.0]
"HYUNDAI_AZERA_6TH_GEN" = [1.8, 1.8, 0.1, 0.0, 0.0]
"HYUNDAI_AZERA_HEV_6TH_GEN" = [1.8, 1.8, 0.1, 0.0, 0.0]
"KIA_K8_HEV_1ST_GEN" = [2.5, 2.5, 0.1, 0.0, 0.0]
"HYUNDAI_CUSTIN_1ST_GEN" = [2.5, 2.5, 0.1, 0.0, 0.0]
"LEXUS_GS_F" = [2.5, 2.5, 0.08, 0.0, 0.0]
"HYUNDAI_STARIA_4TH_GEN" = [1.8, 2.0, 0.15, 0.0, 0.0]
"GENESIS_GV70_ELECTRIFIED_1ST_GEN" = [1.9, 1.9, 0.09, 0.0, 0.0]
"GENESIS_G80_2ND_GEN_FL" = [2.5819356441497803, 2.5, 0.11244568973779678, 0.0, 0.0]
# Note that some Rivians achieve significantly less lateral acceleration than thi, 0.0, 0.0s
"RIVIAN_R1_GEN1" = [2.8, 2.5, 0.07, 0.0, 0.0]
"HYUNDAI_NEXO_1ST_GEN" = [2.5, 2.5, 0.1, 0.0, 0.0]

# Dashcam or fallback configured as ideal ca, 0.0, 0.0r
"MOCK" = [10.0, 10, 0.0, 0.0, 0.0]

# Manually checke, 0.0, 0.0d
"HONDA_CIVIC_2022" = [2.5, 1.2, 0.15, 0.0, 0.0]
"HONDA_HRV_3G" = [2.5, 1.2, 0.2, 0.0, 0.0]
"HONDA_PILOT_4G" = [1.0, 1.0, 0.2, 0.0, 0.0]

"MAZDA_3_2019" = [0.1, 3.0, 0.325, 3.8, 1.0]
"MAZDA_CX_30" = [0.1, 3.0, 0.325, 5.0, 1.0]
"MAZDA_CX_50" = [1.45, 3.0, 0.33, 0.0, 0.0]
